library(ggplot2)
library(knitr)
source("R/helper_functions.R")


#' Creates a codebook
#' 
#' @param df Dataframe from which to construct the codebook
#' 
#' @param outname Base name to be used for output codebook files
#' 
#' @param overwrite if TRUE (default), overwrites existing files
#' 
#' @param reportTitle String to be passed to Codebook as title
#' 
#' @export
#' 

createCodebook <- function(df, outname="examples/test", overwrite=T, reportTitle="My Codebook", output="html"){

  #construct names
  outRmd = paste0(outname, ".Rmd")
  outHtml = paste0(outname, ".html")
  
  
  #delete existing files, if requested
  if (overwrite & file.exists(outRmd)){
    file.remove(outRmd)
  }
  if (overwrite & file.exists(outHtml)){
    file.remove(outHtml)
  }
  
  # Open file connections
  fileConn <<- file(outRmd, "w") 

  ## write YAML preamble
  writer("---")
  writer(paste("title:", reportTitle))
  writer("subtitle: \"Autogenerated data summary from Create Codebook\"")
  writer(paste("date:", Sys.time())) 
  if (output=="pdf") writer("output: pdf_document")
  if (output=="html") writer("output: html_document")
  if (output=="docx") writer("output: word_document")
  writer("---")
  
  ## include packages as a first chunk
  secretChunk.wrapper("library(ggplot2)\nlibrary(pander)")
  
  #Write basic codebook information
  writer("## Basic Information")
  writer("***")
  #write TOC
  writer("## Table of contents")
  writer("***")
  #Main variable loop: for each column, write out results
  varNames <- names(df)
  for (i in 1:length(df)){
    #determine type
    writer(paste0("##", varNames[i]))
    var <- df[i]
    outF <- data.frame(table(var))
    names(outF) <- c("x","y")
   gg <- paste0("ggplot(",deparse(outF),", aes_string(x = 'x', y = 'y')) +
     geom_bar(stat = 'identity')")
   
    row.wrapper("this is one col", fig.wrapper(deparse(gg))) #fig.wrapper("plot(iris$Sepal.Length)"))
    
    # summaryTable <- tableVariable(var)
    # summaryGraphic <- plotVariable(var)
    # 
    writer ("***")
  }
  
  ## Force flush and close connection
  flush(fileConn)
  close(fileConn)
  
  #Knit document
  rmarkdown::render(outRmd, 'html_document', outHtml)
  
}
createCodebook(iris)








